setTimeout(()=>{
    document.getElementById("dispMsg").innerHTML="10";
    document.getElementById("dispMsg").setAttribute("class","even");
    setTimeout(()=>{
        document.getElementById("dispMsg").innerHTML="9";
        document.getElementById("dispMsg").setAttribute("class","odd");
        setTimeout(()=>{
            document.getElementById("dispMsg").innerHTML="8";
            document.getElementById("dispMsg").setAttribute("class","even");
            setTimeout(()=>{
                document.getElementById("dispMsg").innerHTML="7";
                document.getElementById("dispMsg").setAttribute("class","odd");
                setTimeout(()=>{
                    document.getElementById("dispMsg").innerHTML="6";
                    document.getElementById("dispMsg").setAttribute("class","even");
                    setTimeout(()=>{
                        document.getElementById("dispMsg").innerHTML="5";
                        document.getElementById("dispMsg").setAttribute("class","odd");
                        setTimeout(()=>{
                            document.getElementById("dispMsg").innerHTML="4";
                            document.getElementById("dispMsg").setAttribute("class","even");
                            setTimeout(()=>{
                                document.getElementById("dispMsg").innerHTML="3";
                                document.getElementById("dispMsg").setAttribute("class","odd");
                                setTimeout(()=>{
                                    document.getElementById("dispMsg").innerHTML="2";
                                    document.getElementById("dispMsg").setAttribute("class","even");
                                    setTimeout(()=>{
                                        document.getElementById("dispMsg").innerHTML="1";
                                        document.getElementById("dispMsg").setAttribute("class","odd");
                                        setTimeout(()=>{
                                            document.getElementById("dispMsg").innerHTML="Ready";
                                            document.getElementById("dispMsg").setAttribute("class","even");
                                            setTimeout(()=>{
                                                document.getElementById("dispMsg").innerHTML="Happy Independence Day!";
                                                document.getElementById("dispMsg").setAttribute("class","happyText");
                                            },2000);
                                        },2000);
                                    },2000);
                                },2000);
                            },2000);
                        },2000);
                    },2000);
                },2000);
            },2000);
        },2000);
    },2000);
},2000);